# Generated by Django 4.2.11 on 2024-08-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tipo',
            field=models.CharField(choices=[('-', '-'), ('limpeza', 'Limpeza'), ('formatação_backup', 'Formatação e Backup'), ('reparo', 'Reparo'), ('troca_tela', 'Troca de Tela'), ('substituicao_bateria', 'Substituição de Bateria'), ('remocao_virus', 'Remoção de Vírus'), ('atualizacao_sistema', 'Atualização de Sistema'), ('recuperacao_dados', 'Recuperação de Dados')], default='-', max_length=25),
        ),
    ]
