# Generated by Django 4.2.11 on 2024-08-01 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aparelhoApp', '0002_aparelho_descricao_aparelho_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_problema', models.TextField()),
                ('custo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_progresso', 'Em Progresso'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente_notificado', models.BooleanField(default=False)),
                ('aparelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparelhoApp.aparelho')),
            ],
        ),
    ]
