# Generated by Django 4.2.11 on 2024-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='descricao',
            field=models.CharField(default='Descrição padrão', max_length=255),
        ),
        migrations.AddField(
            model_name='aparelho',
            name='nome',
            field=models.CharField(default='nome', max_length=100),
        ),
    ]
