# Generated by Django 4.2.11 on 2024-08-23 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clienteApp', '0004_remove_cliente_sexo'),
        ('aparelhoApp', '0002_aparelho_descricao_aparelho_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clienteApp.cliente'),
        ),
    ]
