# Generated by Django 4.2.11 on 2024-08-15 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferramenta',
            options={'ordering': ['nome'], 'verbose_name': 'Ferramenta', 'verbose_name_plural': 'Ferramentas'},
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
