# Generated by Django 4.2.11 on 2024-08-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentaApp', '0002_alter_ferramenta_options_alter_ferramenta_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramenta',
            name='fornecedor',
        ),
    ]
