# Generated by Django 4.2.11 on 2024-08-05 18:45

import cpf_field.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('cargo', models.CharField(choices=[('-', '-'), ('atendente', 'Atendente'), ('técnico', 'Técnico')], default='-', max_length=20)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionario',
                'ordering': ['nome'],
            },
        ),
    ]
