# Generated by Django 4.2.11 on 2024-08-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecaApp', '0002_alter_peca_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='preco_compra',
            field=models.FloatField(),
        ),
    ]
