# Generated by Django 4.2.11 on 2024-08-14 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
