# Generated by Django 4.2.11 on 2024-08-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedorApp', '0002_fornecedor_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='data_cadastro',
        ),
    ]
