# Generated by Django 4.2.11 on 2024-08-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clienteApp', '0003_cliente_sexo_alter_cliente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sexo',
        ),
    ]
