# Generated by Django 4.2.11 on 2024-07-17 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('cod_barras', models.CharField(max_length=130, unique=True)),
                ('Preco', models.FloatField()),
                ('categoria', models.CharField(max_length=250)),
                
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome', 'preco'],
            },
        ),
    ]
