# Generated by Django 4.2.11 on 2024-08-19 02:16

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('produtosApp', '0002_produto_descricao_produto_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Preco',
            new_name='preco',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(
                default='Categoria do produto', max_length=255),
        ),
    ]
